# Generated by Django 5.1.1 on 2024-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dis_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
